linters:
  disable-all: true
  enable:
    - goimports
    - golint
    - govet
linters-settings:
  govet:
    check-shadowing: true

issues:
  exclude-use-default: false
  exclude-rules:
    - EXC0002
